SELECT 
    R.DEPARTAMENTO AS "Nombre Departamento",
    COUNT(R.EMPREGADO) AS "Cantidad Empleados",
    CASE 
        WHEN ROUND(SUM(R.LIQUIDO) * 1.0 / COUNT(R.EMPREGADO), 2) = 0 THEN '0'
        ELSE CAST(ROUND(SUM(R.LIQUIDO) * 1.0 / COUNT(R.EMPREGADO), 2) AS TEXT)
    END AS "Promedio Salarial",
    CASE 
        WHEN MAX(R.LIQUIDO) = 0 THEN '0'
        ELSE CAST(MAX(R.LIQUIDO) AS TEXT)
    END AS "Salario Máximo",
    CASE 
        WHEN MIN(R.LIQUIDO) = 0 THEN '0'
        ELSE CAST(MIN(R.LIQUIDO) AS TEXT)
    END AS "Salario Mínimo"
FROM (
    SELECT 
        DEP.NOME AS DEPARTAMENTO,
        EMP.NOME AS EMPREGADO,
        ROUND(
            COALESCE((
                SELECT SUM(V.VALOR)
                FROM DEPARTAMENTO DEPAR
                INNER JOIN DIVISAO DIVIS ON DEPAR.COD_DEP = DIVIS.COD_DEP
                INNER JOIN EMPREGADO EMPRE ON DIVIS.COD_DIVISAO = EMPRE.LOTACAO_DIV
                INNER JOIN EMP_VENC EV ON EMPRE.MATR = EV.MATR
                INNER JOIN VENCIMENTO V ON EV.COD_VENC = V.COD_VENC
                WHERE EMPRE.NOME = EMP.NOME
            ), 0), 2) -
        COALESCE((
            SELECT SUM(D.VALOR)
            FROM DEPARTAMENTO DEPA
            INNER JOIN DIVISAO DIVI ON DEPA.COD_DEP = DIVI.COD_DEP
            INNER JOIN EMPREGADO EMPR ON DIVI.COD_DIVISAO = EMPR.LOTACAO_DIV
            INNER JOIN EMP_DESC ED ON EMPR.MATR = ED.MATR
            INNER JOIN DESCONTO D ON ED.COD_DESC = D.COD_DESC
            WHERE EMPR.NOME = EMP.NOME
        ), 0) AS LIQUIDO
    FROM 
        DEPARTAMENTO DEP
        INNER JOIN DIVISAO DIV ON DEP.COD_DEP = DIV.COD_DEP
        INNER JOIN EMPREGADO EMP ON DIV.COD_DIVISAO = EMP.LOTACAO_DIV
    GROUP BY 
        DEP.NOME, EMP.NOME
) R
GROUP BY R.DEPARTAMENTO
ORDER BY "Promedio Salarial" DESC;
